# Generated by Django 6.0.3 on 2026-04-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
