# Generated by Django 6.0.3 on 2026-04-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='location',
            field=models.CharField(choices=[('Kimberley CBD', 'Kimberley CBD'), ('Galeshewe', 'Galeshewe'), ('Roodepan', 'Roodepan'), ('Cassandra', 'Cassandra'), ('Homevale', 'Homevale'), ('New Park', 'New Park')], default='Kimberley CBD', max_length=50),
        ),
    ]
